### ISSUE TITLE
Does not compile on clang-3.4 or gcc 4.8

### ISSUE THREAD

**Issue by Saulzar** [nvpro-pipeline/vkcpp#70]
Am I missing something here?

g++-4.8

/home/oliver/Projects/vkcpp/VkCppGenerator.cpp: In function ‘int main(int, char**)’:
/home/oliver/Projects/vkcpp/VkCppGenerator.cpp:2719:30: error: no matching function for call to ‘std::vector<DependencyData>::erase(std::vector<DependencyData>::const_iterator&)’
   sortedDependencies.erase(it);

clang++-3.4

/home/oliver/Projects/vkcpp/VkCppGenerator.cpp:2719:22: error: no matching member function for call to 'erase'
  sortedDependencies.erase(it);
  ~~~~~~~~~~~~~~~~~~~^~~~~
/usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/bits/stl_vector.h:1075:7: note: candidate function not viable: no known conversion from
      '__normal_iterator<const_pointer, [...]>' to '__normal_iterator<pointer, [...]>' for 1st argument
      erase(iterator __position);
      ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/bits/stl_vector.h:1096:7: note: candidate function not viable: requires 2 arguments, but 1 was provided
      erase(iterator __first, iterator __last);

**Comment by mtavenrath** [comment]
@Saulzar,
the error message looks like C++11 is not enabled in the compiler since the missing function is part of C++11, see http://www.cplusplus.com/reference/vector/vector/erase/

Do you use the provided cmakelists.txt? This one should enable the C++11 mode for gcc/clang.

**Comment by Saulzar** [comment]
Yeah, I'm using the provided cmakelists - I'm on ubuntu 14.04 with cmake 3.2.

It compiles if I change line 2715 to a in iterator rather than a const_interator.

**Comment by asuessenbach** [comment]
And that's what makes us think, you're not on C++11. With C++11, the support of const_iterator on std::vector::erase() was added.

**Comment by omaressa** [comment]
@Saulzar  - Enable c++11  -std=c++11

**Comment by mtavenrath** [comment]
No further response, assuming that it's working.
